AWSTemplateFormatVersion: 2010-09-09
Description: Create EmrJobReporting envinroment
Parameters:
  emrJobReportingS3Bucket:
    Type: String
    Default: here-oneworld-dev
    Description: The main bucket where all deployment data was uploaded.
  emrJobRegistrationJarS3Key:
      Type: String
      Default: aluptak/emrJopReporter/emr-job-registration-1.0-SNAPSHOT.jar
      Description: Key under the bucket where is jar for emrJobRegistrationHandler lambda.
  emrJobReportingIAMRole:
        Type: String
        Default: ""
        Description: Role for lambda function in AWS.
  emrJobMessageCollectorJarS3Key:
        Type: String
        Default: aluptak/emrJopReporter/emr-job-message-collector-1.0-SNAPSHOT.jar
        Description: Key under the bucket where is jar for emrJobMessageCollector lambda.
  emrJobStateUpdaterJarS3Key:
        Type: String
        Default: aluptak/emrJopReporter/emr-job-state-updater-1.0-SNAPSHOT.jar
        Description: Key under the bucket where is jar for emrJobStateUpdater lambda.
  s3UserHtmlReporterJarS3Key:
          Type: String
          Default: aluptak/emrJopReporter/s3-user-html-reporter-1.0-SNAPSHOT.jar
          Description: Key under the bucket where is jar for emrJobStateUpdater lambda.
  s3DevHtmlReporterJarS3Key:
          Type: String
          Default: aluptak/emrJopReporter/s3-dev-html-reporter-1.0-SNAPSHOT.jar
          Description: Key under the bucket where is jar for emrJobStateUpdater lambda.
  lambdaSecurityGroup:
          Default: sg-42832a3e
          Type: List<AWS::EC2::SecurityGroup::Id>
          Description: Security groups to apply to the RDS cluster.
  lambdaSubnets:
          Default: "subnet-4d98bb67,subnet-bd3ddcf4"
          Description: The subnets to place database instances in.
          Type: List<AWS::EC2::Subnet::Id>
Resources:
  emrJobRegistrationHandler:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket:
          Ref: emrJobReportingS3Bucket
        S3Key:
          Ref: emrJobRegistrationJarS3Key
      Description: "This lambda handler is triggered with SNS and save new emr job cluster info to emr reporting database"
      FunctionName: "emrJobRegistrationHandler"
      Handler: "com.here.owc.EmrJobRegistrationHandler::handleRequest"
      MemorySize: 512
      Role:
        Ref: emrJobReportingIAMRole
      Runtime: "java8"
      Timeout: 20
      VpcConfig:
        SecurityGroupIds:
            Ref: lambdaSecurityGroup
        SubnetIds:
            Ref: lambdaSubnets
  emrJobRegistrationSnsTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      DisplayName: ejrt
      Subscription:
      -
        Endpoint: !GetAtt emrJobRegistrationHandler.Arn
        Protocol: "lambda"
      TopicName: "emrJobRegistrationTopic"
  LambdaResourcePolicy:
      Type: "AWS::Lambda::Permission"
      Properties:
        Action: "lambda:InvokeFunction"
        FunctionName: !GetAtt emrJobRegistrationHandler.Arn
        Principal: "sns.amazonaws.com"
        SourceArn: !Ref emrJobRegistrationSnsTopic
  EmrJobMessageCollectorHandler:
      Type: "AWS::Lambda::Function"
      Properties:
        Code:
          S3Bucket:
            Ref: emrJobReportingS3Bucket
          S3Key:
            Ref: emrJobMessageCollectorJarS3Key
        Description: "This lambda handler will be triggered by cloudWatch scheduled event"
        FunctionName: "emrJobMessageCollector"
        Handler: "com.here.owc.EmrJobMessageCollectorHandler::handleRequest"
        MemorySize: 512
        Role:
          Ref: emrJobReportingIAMRole
        Runtime: "java8"
        VpcConfig:
                SecurityGroupIds:
                    Ref: lambdaSecurityGroup
                SubnetIds:
                    Ref: lambdaSubnets
  emrJobMessageCollectorScheduledEvent:
      Type: "AWS::Events::Rule"
      Properties:
        Description: "Every desired interval lambda function emrJobMessageCollector will be triggered"
        Name: "emrJobMessageCollectorScheduledEvent"
        ScheduleExpression: "rate(1 minute)"
        Targets:
          -
            Arn: !GetAtt EmrJobMessageCollectorHandler.Arn
            Id: "emrJobMessageCollectorScheduledEvent"
  emrJobMessageCollectorResourcePolicy:
        Type: "AWS::Lambda::Permission"
        Properties:
          Action: "lambda:InvokeFunction"
          FunctionName: !GetAtt EmrJobMessageCollectorHandler.Arn
          Principal: "events.amazonaws.com"
          SourceArn: !GetAtt emrJobMessageCollectorScheduledEvent.Arn
  emrJobStateUpdater:
        Type: "AWS::Lambda::Function"
        Properties:
          Code:
            S3Bucket:
              Ref: emrJobReportingS3Bucket
            S3Key:
              Ref: emrJobStateUpdaterJarS3Key
          Description: "This lambda handler will be triggered by cloudWatch EMR event"
          FunctionName: "emrJobStateUpdater"
          Handler: "com.here.owc.EmrJobStateUpdaterHandler::handleRequest"
          MemorySize: 512
          Role:
            Ref: emrJobReportingIAMRole
          Runtime: "java8"
          VpcConfig:
                  SecurityGroupIds:
                      Ref: lambdaSecurityGroup
                  SubnetIds:
                      Ref: lambdaSubnets
  emrJobStateUpdaterEvent:
      Type: "AWS::Events::Rule"
      Properties:
        Description: "Every desired interval lambda function emrJobMessageCollector will be triggered"
        EventPattern:
          {
            "source": [
              "aws.emr"
            ],
            "detail-type": [
              "EMR Cluster State Change"
            ]
          }
        Name: "emrJobStateUpdaterEvent"
        Targets:
          -
            Arn: !GetAtt emrJobStateUpdater.Arn
            Id: "emrJobStateUpdaterEvent"
  emrJobStateUpdaterResourcePolicy:
          Type: "AWS::Lambda::Permission"
          Properties:
            Action: "lambda:InvokeFunction"
            FunctionName: !GetAtt emrJobStateUpdater.Arn
            Principal: "events.amazonaws.com"
            SourceArn: !GetAtt emrJobStateUpdaterEvent.Arn
  s3UserHtmlReporterHandler:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket:
          Ref: emrJobReportingS3Bucket
        S3Key:
          Ref: s3UserHtmlReporterJarS3Key
      Description: "This lambda handler is triggered with SNS and create new html dev report contains detail messages"
      FunctionName: "s3UserHtmlReport"
      Handler: "com.here.owc.S3UserHtmlReporterHandler::handleRequest"
      MemorySize: 512
      Role:
        Ref: emrJobReportingIAMRole
      Runtime: "java8"
      VpcConfig:
              SecurityGroupIds:
                  Ref: lambdaSecurityGroup
              SubnetIds:
                  Ref: lambdaSubnets
  s3DevHtmlReporterHandler:
      Type: "AWS::Lambda::Function"
      Properties:
        Code:
          S3Bucket:
            Ref: emrJobReportingS3Bucket
          S3Key:
            Ref: s3DevHtmlReporterJarS3Key
        Description: "This lambda handler is triggered with SNS and create user html report for average user"
        FunctionName: "s3DevHtmlReporterHandler"
        Handler: "com.here.owc.S3DevHtmlReporterHandler::handleRequest"
        MemorySize: 512
        Role:
          Ref: emrJobReportingIAMRole
        Runtime: "java8"
        VpcConfig:
                SecurityGroupIds:
                    Ref: lambdaSecurityGroup
                SubnetIds:
                    Ref: lambdaSubnets
  emrJobReportSnsTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      DisplayName: ejr
      Subscription:
      -
        Endpoint: !GetAtt s3DevHtmlReporterHandler.Arn
        Protocol: "lambda"
      -
        Endpoint: !GetAtt s3UserHtmlReporterHandler.Arn
        Protocol: "lambda"
      TopicName: "emrJobReportTopic"
  s3DevHtmlReporterResroucePolicy:
      Type: "AWS::Lambda::Permission"
      Properties:
        Action: "lambda:InvokeFunction"
        FunctionName: !GetAtt s3DevHtmlReporterHandler.Arn
        Principal: "sns.amazonaws.com"
        SourceArn: !Ref emrJobReportSnsTopic
  s3UserHtmlReporterResroucePolicy:
        Type: "AWS::Lambda::Permission"
        Properties:
          Action: "lambda:InvokeFunction"
          FunctionName: !GetAtt s3UserHtmlReporterHandler.Arn
          Principal: "sns.amazonaws.com"
          SourceArn: !Ref emrJobReportSnsTopic
